#!/bin/bash
#
# For running on the CSEM cluster Sverdrup
#  Compiler optimizations for Intel E5-2695 v3 (Haswell) Processors
#  Note: only difference from lonestar opt file is the netcdf module load
#
# Note: be sure to load the following modules
#
#  module load intel/18.0
#  module load openmpi
#
#-------

CC=icc
FC=ifort
F90C=mpifort
LINK="$F90C -no-ipo"

DEFINES='-DALLOW_USE_MPI -DALWAYS_USE_MPI -DWORDLENGTH=4'
CPP='cpp -traditional -P'
F90FIXEDFORMAT='-fixed -Tf'
EXTENDED_SRC_FLAG='-132' # after chacater position 132 is invisible to *.F
GET_FC_VERSION="--version"
OMPFLAG='-openmp'

NOOPTFILES='-01 -fp-model precise -g -xCORE-AVX2'

FFLAGS="$FFLAGS -W0 -WB -convert big_endian -assume byterecl"
FFLAGS="$FFLAGS -fPIC -no-wrap-margin"
FFLAGS="$FFLAGS -mcmodel=large -shared-intel"
FFLAGS="$FFLAGS -132" # extend to 132 columns

if test "x$IEEE" = x ; then     #- with optimisation:
    FOPTIM='-O2 -align -traceback -xCORE-AVX2 -ip -ftz -fp-model precise'
    NOOPTFILES='seaice_init_varia.F'
else
  if test "x$DEVEL" = x ; then  #- no optimisation + IEEE :
    FOPTIM='-O0 -noalign -traceback -xCORE-AVX2 -ip -mp'
  else                          #- development/check options:
    FFLAGS="$FFLAGS -warn all -warn nounused"
    FOPTIM="-fpe0 -fpstkchk -fpmodel except -check all -ftrapuv"
    FOPTIM="-O0 -noalign -g -traceback"
  fi
fi

F90FLAGS=$FFLAGS
F90OPTIM=$FOPTIM
CFLAGS='-O0 -ip -fPIC'

INCLUDEDIRS="${MPI_DIR}/include ${NETCDF_FORTRAN_INC} ${NETCDF_INC}"
INCLUDES="-I${MPI_DIR}/include -I${NETCDF_FORTRAN_INC} -I${NETCDF_INC}"
LIBS="-I${MPI_DIR}/lib -Wl,-rpath -Wl,${MPI_DIR}/lib -Wl,--enable-new-dtags -L${MPI_DIR}/lib -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi -L${NETCDF_FORTRAN_LIB} -L${NETCDF_LIB} -lnetcdf -lnetcdff"
